spring:
    jpa:
      generate-ddl: 'false'
      database: mysql
      hibernate:
        naming:
          strategy: org.hibernate.cfg.ImprovedNamingStrategy
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: none
      show-sql: 'false'
      properties:
        hibernate:
          enable_lazy_load_no_trans: 'true'
          format_sql: 'true'
      database-platform: org.hibernate.dialect.MySQL8Dialect

    datasource:
      password: !!binary |-
        w6vCucKEw6vCsMKAw6vCssKIw63CmMK4
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: !!binary |-
        w6zClcKEw6zCncK0w6vClMKU
      url: jdbc:mysql://localhost:3306/goapi?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
